added routes
UC-Technologies/vyatha-UI pull request #11
Opened 2023-09-14 06:21 UTC by zordican

Added routes

2023-09-14 18:43 UTC, Himangshu-101 commented on src/Components/StudentStyle.scss
> +}
this block is redundant and avoid selecting the whole body or *

2023-09-14 18:45 UTC, Himangshu-101 commented on src/App.jsx
> +          <Route path="/login/student" element={<StudentLogin />}></Route>
use exact path here

2023-09-14 18:47 UTC, Himangshu-101 commented on src/App.jsx
> +const App = () => {
why did you change function to const . You can specify your reason here

2023-09-14 19:04 UTC, Himangshu-101 requested changes

2023-09-14 19:04 UTC, Himangshu-101 commented on src/Components/StudentStyle.scss
rename it to module.scss file name

2023-09-20 05:30 UTC, zordican commented on src/Components/StudentStyle.scss
> +}
okay bhaiya

2023-09-20 05:31 UTC, zordican commented on src/App.jsx
> +          <Route path="/login/student" element={<StudentLogin />}></Route>
okay bhaiya

2023-09-22 19:19 UTC, hereisadi requested changes

2023-09-22 19:19 UTC, hereisadi commented on src/Components/module.scss
found use of px. use relative font units instead.

2023-09-22 19:19 UTC, hereisadi commented on src/App.jsx
> +      <div>
no need to wrap routes inside div.

2023-09-22 19:19 UTC, hereisadi commented on src/Components/module.scss
> +@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;700&display=swap");
redundant import. Poppins has already been imported in index.scss

2023-09-22 19:19 UTC, hereisadi commented on src/Components/module.scss
> +  font-family: "poppins", sans-serif;
use the variable ` --vyatha-font-1` for Poppins as specified in index.scss

2023-09-26 14:07 UTC, hereisadi requested changes

2023-09-26 14:07 UTC, hereisadi commented on src/Components/StudentSignUp.jsx
> +        <div className="form">
you have to className like:
`className = {styles.form}`

2023-09-26 14:07 UTC, hereisadi commented on src/Components/StudentSignUp.jsx
> +import "./StudentSignUp.module.scss";
correct way:
`import styles from "./StudentSignUp.module.scss";`

2023-10-17 12:55 UTC, closed without merging