created first page
UC-Technologies/vyatha-UI pull request #12
Opened 2023-09-14 06:24 UTC by tensorwarriormayank880

student admin page

2023-09-14 20:27 UTC, hereisadi requested changes

2023-09-14 20:27 UTC, hereisadi commented on src/Components/LoginPage/Login.scss
it should be login.module.scss

2023-09-14 20:27 UTC, hereisadi commented on src/Components/shared/Navbar/Navbar.jsx
unnecessary changes

2023-09-21 08:02 UTC, hereisadi commented
take pull of `dev` @tensorwarriormayank880

2023-09-24 19:24 UTC, tensorwarriormayank880 commented
newChanges

2023-09-26 13:49 UTC, hereisadi requested changes

2023-09-26 13:49 UTC, hereisadi commented on package.json
> +    "scss": "^0.2.4"
no need to install scss. sass has already been listed in dev devDependencies

2023-09-26 13:49 UTC, hereisadi commented on src/Components/LoginPage/Comp.json
put the lottie json in `public` folder.

2023-09-26 13:49 UTC, hereisadi commented on src/Components/LoginPage/Authentication.scss
fileName should be Authentication.module.scss.

2023-09-26 13:49 UTC, hereisadi commented on src/Components/LoginPage/Authentication.scss
> +
Also use relative font units only

2023-09-26 13:50 UTC, hereisadi commented
ping @tensorwarriormayank880

2023-10-12 12:55 UTC, hereisadi approved these changes

2023-10-18 19:20 UTC, closed without merging