Add
UC-Technologies/vyatha-UI pull request #15
Opened 2023-09-17 05:42 UTC by coderp233

Added the Sign up Admin page, scss styling and enable button

2023-09-18 19:27 UTC, hereisadi requested changes

2023-09-18 19:27 UTC, hereisadi commented on src/Components/SignupAdmin/SignupAdmin.scss
use relative units

2023-09-18 19:27 UTC, hereisadi commented on src/App.jsx
solve all ESLint issues in all files

2023-09-24 14:21 UTC, hereisadi requested changes

2023-09-24 14:21 UTC, hereisadi commented on src/Components/SignupAdmin/SignupAdmin.jsx
> +        <div className="admin-form">
you have to use className like:
className = {styles.admin_form}

2023-09-24 14:21 UTC, hereisadi commented on src/Components/SignupAdmin/SignupAdmin.jsx
> +import './SignupAdmin.scss'
import like:
import styles from './Signup.module.scss'

2023-09-24 14:21 UTC, hereisadi commented on src/Components/SignupAdmin/SignupAdmin.scss
create scss file like:
SignupAdmin.module.scss

2023-09-24 14:21 UTC, hereisadi commented on src/Components/SignupAdmin/SignupAdmin.jsx
> +  <select id='Designation1' name="design" className="select_step" style={{width:'326px', height:'40px',position: "relative", top: "-22px"}} >
use relative units. for eg: `rem`, `vw`, `vh` etc

2023-10-11 21:08 UTC, Himangshu-101 requested changes

2023-10-11 21:08 UTC, Himangshu-101 commented on src/Components/SignupAdmin/SignupAdmin.jsx
> +        <label for="control1" className={styles.Placeholder}>Email</label>
use htmlFor only for ReactJS. 'for' is a reserved keyword in JS
Use this in all occurring cases in this or other files too

2023-10-11 21:08 UTC, Himangshu-101 commented on src/Components/SignupAdmin/SignupAdmin.jsx
> +<label For="control5" >Designation</label>
JS, ReactJS are case sensitive, 'For' is not a word in either.
Use 'htmlFor' here

2023-10-11 21:08 UTC, Himangshu-101 commented on src/Components/SignupAdmin/SignupAdmin.jsx
> +        <label id="control4" className={styles.Placeholder}>Confirm Password</label>
add htmlFor

2023-10-12 17:20 UTC, ankit07an approved these changes

2023-12-23 13:40 UTC, closed without merging