First Changes Commited
UC-Technologies/vyatha-UI pull request #18
Opened 2023-10-18 19:46 UTC by tensorwarriormayank880

Created first page for both admin and student and next page of login and signup.

2023-11-01 15:25 UTC, Himangshu-101 requested changes

2023-11-01 15:25 UTC, Himangshu-101 commented on src/Pages/Auth/Admin/Admin.jsx
> +              <p>
Give proper spaces here according to the design

2023-11-01 15:25 UTC, Himangshu-101 commented on src/Pages/Auth/Admin/Admin.jsx
> +                  src="https://res.cloudinary.com/dlx4meooj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1695295732/login_w7ltqc.jpg?_s=public-apps"
increase the logo size so that it looks better. Compare with the figma design

2023-11-01 15:25 UTC, Himangshu-101 commented on src/Pages/Auth/Auth.jsx
> +            <button className={styles.student_div} onClick={handleStudent}>
pointer : cursor on hover

2023-11-01 15:25 UTC, Himangshu-101 commented on src/Pages/Auth/Student/Student.jsx
> +                Don&apos;t have an account? <Link to="/auth/student/signup">Sign up</Link>
Same issues as above. Correct the spacings and letter sizes

2023-11-01 18:44 UTC, tensorwarriormayank880 commented on src/Pages/Auth/Auth.jsx
> +            <button className={styles.student_div} onClick={handleStudent}>
All Done.

2023-11-10 12:14 UTC, Himangshu-101 approved these changes

2023-12-10 09:37 UTC, hereisadi approved these changes

2023-12-10 09:37 UTC, merged