Adding Complaint Form
UC-Technologies/vyatha-UI pull request #9
Opened 2023-09-13 18:18 UTC by PragyaPR06

Things to do:
1)Style the dropdown arrow element of select tag
2)Add the loader for the image upload

2023-09-13 21:56 UTC, hereisadi requested changes

2023-09-13 21:56 UTC, hereisadi commented on src/App.jsx
The filename "multipleinputs.jsx"should be in "PASCAL_CASE" pattern

2023-09-13 21:56 UTC, hereisadi commented on src/App.jsx
> +            <Route exact path="/Complaintform" element={<CForm />} />
route "/complaintform" should be in lower case

2023-09-13 21:56 UTC, hereisadi commented on src/Components/Shared/Form/multipleinputs.jsx
> +    const[Formdata,setformdata]=useState({
although the way you wrote would work, but the proper syntax of using useState Hook is:
const [formData, setFormData] = useState({})

2023-09-13 21:56 UTC, hereisadi commented on src/Components/Shared/Form/multipleinputs.jsx
> +    const[Storedata,setstoredata]=useState([]);
same syntax issue with useState

2023-09-13 21:56 UTC, hereisadi commented on src/Components/Shared/Form/multipleinputs.jsx
> +export default function CForm(){
Use arrow function: (everywhere)
const CForm = () => {}
export default CForm;

2023-09-13 21:56 UTC, hereisadi commented on src/Components/Shared/Form/multipleinputs.jsx
> +            ...Formdata,
use functional update form of setFormData

2023-09-13 21:56 UTC, hereisadi commented on src/Components/Shared/Form/multipleinputs.jsx
> +                                            <img src="https://res.cloudinary.com/dlx4meooj/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1694535132/UC%20VYATHA/Frame_58066_1_nnkr62.
img is self closing tag. no need to add explicit closing tag

2023-09-13 21:56 UTC, hereisadi commented on src/Components/Shared/Form/multipleinputs.jsx
> +                                            <input type="file" name="Imagefile" id="imagebrowse" accept=".jpg, .jpeg, .png" onChange={handleFileInputChange}  required />
accept webp file too

2023-09-13 21:56 UTC, hereisadi commented on src/Components/Shared/Form/multipleinputs.jsx
> +        if(file){
use try catch block for exceptional error handling and if file size is greater than say 250KB throw an alert with proper error msg

2023-09-13 21:56 UTC, hereisadi commented on src/App.jsx
![image](https://github.com/UC-Technologies/vyatha-UI/assets/106585924/72cb21af-80ef-4c29-905b-a5b29a7a3a24)
select parent's div width is overflowing

2023-09-13 21:56 UTC, hereisadi commented on src/Components/Shared/Form/styleform.module.scss
> +            background: linear-gradient(270deg, #40BDB6 2.67%, #347EC5 119.87%);
declare the gradient in index.scss and use it using var()

2023-09-13 21:56 UTC, hereisadi commented on src/Components/Shared/Form/styleform.module.scss
> +body {
don't apply styling to body directly.

2023-09-13 21:56 UTC, hereisadi commented on src/Components/Shared/Form/styleform.module.scss
> +    padding: 0;
redundant code. margin and padding has already been set to zero in index.scss

2023-09-13 21:56 UTC, hereisadi commented on src/Components/Shared/Form/styleform.module.scss
> +            padding: 20px;
use relative font units

2023-09-26 14:34 UTC, hereisadi commented
remaining conversation changes has not been fixed yet. @PragyaPR06

2023-09-26 14:35 UTC, hereisadi requested changes

2023-09-26 14:35 UTC, hereisadi commented on src/Components/Shared/Form/MultipleInputs.jsx
> +/* eslint-disable */
no need to disable the eslint

2023-10-10 10:25 UTC, Himangshu-101 commented on src/Components/Shared/Form/MultipleInputs.jsx
> +              <option value="PGH" id="PGH" name="Hostel" onChange={handleInput}>
why did you give PGH in name and value for gh1, gh2, gh3 ?
wouldn't it be different for each ?

2023-10-10 10:31 UTC, Himangshu-101 submitted a review, later dismissed

2023-10-12 13:16 UTC, hereisadi approved these changes

2023-10-15 12:19 UTC, merged